name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: AKIAVWABJTFV4RVELA34
          AWS_SECRET_ACCESS_KEY: MfiUvi2vxovkJYq8AZZs9qnRG9lRit7AAZa35zau
        run: |
          aws s3 sync ./dist s3://kjyn-vue-sample --delete
